### ISSUE TITLE
Using custom folder

### ISSUE THREAD

**Issue by khinshankhan** [shines77/jekyll-emoji#1]
I was wondering how to use the github emoji + a custom folder's. I have my files under `/assets/imgs/emoji/`, and I essentially copy pasted the configuration provided, modifying only the paths:
```
emoji:
  src: "https://github.githubassets.com/images/icons/"

jekyll_plus:
  host: ''
  path: '/assets/imgs/emoji/'

  image:
    class: 'emoji'    # The emoji's css class name. 'emoji' (default)
    ext_name: 'png'   # The emoji's image file extension. 'png' (default), 'jpg', 'jpeg', 'svg'
    width: 20         # The emoji's image width. 20 (default)
    height: 20        # The emoji's image height. 20 (default)

  format:
    image_src: '[image-baseurl][image-filename].[image-extname]'

    emoji_html: '<img class="[emoji-class]" title="[emoji-name]" alt="[emoji-name]" src="[emoji-image-src]" width="[emoji-width]" height="[emoji-height] />'
```
